message = 'hello world'
print (len(message))
print (message[0])
print (message[10])
#print (message[11])
print (message[0:5])
print (message[:5])
print (message[6:])
print (message.lower())
print (message.upper())
print (message.count('hello'))
print (message.count('l'))
print (message.find('world'))
message = message.replace('world','universe')
print (message)

